
import com.sun.rowset.internal.Row;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;

/*
 * View.java
 *
 * Created on 24/11/2011, 10:12:52
 */

/**
 *
 * @author paulocezar
 */



public class View extends javax.swing.JFrame {

    private static String conf_filename = ".seginf_config";
    /** Creates new form View */
    public View(){
        initComponents();

        this.addWindowListener( new WindowAdapter() {  
            @Override
            public void windowClosing(WindowEvent e) {
                try{

                    PrintWriter writer = new PrintWriter( new FileWriter(conf_filename) );


                    if( DA.isSelected() ) writer.println("permit");
                    else writer.println( "deny" );

                    ((SegInfTable)tabela.getModel()).save_data(writer);

                    writer.close();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });

        try{

            File conf_file = new File(conf_filename);
            BufferedReader reader = new BufferedReader(
                                            new FileReader( conf_file ));
            String line = null;
            while((line = reader.readLine()) != null) {

                ArrayList<Object> data = new ArrayList<Object>();

                StringTokenizer tokenizer = new StringTokenizer(line);

                while( tokenizer.hasMoreTokens() ){
                    String token = tokenizer.nextToken();
                    if( token.equals("permit") ){
                        DA.setSelected(true);
                        DAActionPerformed(null);
                    } else if( token.equals("deny") ){
                        DD.setSelected(true);
                    } else {
                        data.add(token);
                    }
                }

                if( !data.isEmpty() ) ((SegInfTable)tabela.getModel()).addRow(data);

            }

            reader.close();
        } catch (FileNotFoundException ex){
            DD.setSelected(true);
        } catch (IOException eex){
            eex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DD = new javax.swing.JRadioButton();
        DA = new javax.swing.JRadioButton();
        addRule = new javax.swing.JButton();
        scrolltpane = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SegINF Firewall");

        DD.setText("Default Deny");
        DD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DDActionPerformed(evt);
            }
        });

        DA.setText("Default Permit");
        DA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAActionPerformed(evt);
            }
        });

        addRule.setText("Adicionar Nova Regra");
        addRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRuleActionPerformed(evt);
            }
        });

        tabela.setModel(new SegInfTable());
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        scrolltpane.setViewportView(tabela);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(DA)
                            .add(DD))
                        .add(18, 18, 18)
                        .add(addRule, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(scrolltpane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(scrolltpane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 298, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(DD)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(DA))
                    .add(addRule, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void addRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRuleActionPerformed
        ((SegInfTable)tabela.getModel()).showInputWindow();
    }//GEN-LAST:event_addRuleActionPerformed

    private void DDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DDActionPerformed
        DA.setSelected(false);
        ((SegInfTable)tabela.getModel()).send_command( "default deny" );
    }//GEN-LAST:event_DDActionPerformed

    private void DAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAActionPerformed
        DD.setSelected(false);
        ((SegInfTable)tabela.getModel()).send_command( "default accept" );
    }//GEN-LAST:event_DAActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int rule_id = tabela.getSelectedRow()+1;
        int answer = JOptionPane.showConfirmDialog( this,
                         "Realmente deseja deletar a regra " + rule_id + " ?",
                         "Confirm",
                         JOptionPane.YES_NO_OPTION,
                         JOptionPane.QUESTION_MESSAGE );

        if( answer == JOptionPane.YES_OPTION ){
            ((SegInfTable)tabela.getModel()).deleteRow(rule_id-1);
            JOptionPane.showMessageDialog(null, "Regra removida com sucesso.", "Finalizado", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_tabelaMouseClicked


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DA;
    private javax.swing.JRadioButton DD;
    private javax.swing.JButton addRule;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane scrolltpane;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

}
